# example with values used in docker compose

addr = "0.0.0.0:4433"
logs = "/var/log/yappa/chat"

[tls]
cert = "/certs/server/server.crt"
key = "/certs/server/server.key"

[ca]
addr = "yappacad:4434"
cert = "/certs/ca/ca.crt"