# example with values used in docker compose

addr = "0.0.0.0:4434"
logs = "/var/log/yappa/ca"
cacert = "/certs/ca/ca.crt"
key = "/certs/ca/ca.key"

[tls]
cert = "/certs/ca_tls/ca_tls.crt"
key = "/certs/ca_tls/ca_tls.key"

[chat]
cert = "/certs/server/server.crt"