FROM debian:bookworm-slim

RUN mkdir -p /var/log/yappa/chat
RUN mkdir -p /etc/yappa
COPY bin/yappacad /usr/local/bin/yappacad
RUN chmod +x /usr/local/bin/yappacad

CMD ["/usr/local/bin/yappacad", "-config", "/etc/yappa/yappacad.toml"]