FROM debian:bookworm-slim

RUN mkdir -p /var/log/yappa/ca
RUN mkdir -p /etc/yappa
COPY bin/yappad /usr/local/bin/yappad
RUN chmod +x /usr/local/bin/yappad

CMD ["/usr/local/bin/yappad", "-config", "/etc/yappa/yappad.toml"]
