// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

type ChatInbox struct {
	Code             []byte
	CurrentTokenHash []byte
	EncToken         []byte
	KeyExchangeData  []byte
}

type ChatInboxMessage struct {
	ID        int32
	SerialN   int64
	InboxCode []byte
	EncMsg    []byte
}

type User struct {
	ID             int32
	Username       string
	Certificate    string
	PubKeyExchange []byte
}

type UserInbox struct {
	ID              int32
	Username        string
	EncSender       []byte
	EncSignature    []byte
	EncSerial       []byte
	EncInboxCode    []byte
	KeyExchangeData []byte
}
